drop table if exists Book;
drop table if exists Person;

create table Person(
                       id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name varchar(100) NOT NULL,
                       birthDate date
);

truncate table Person;

insert into Person(name, birthDate)
VALUES ('Вадим', '1973-08-13'),
       ('Елена', null),
       ('Кирилл', null),
       ('Сергей', '1997-11-23');

select * from Person;

drop table if exists Book;

create table Book(
                     id int GENERATED BY DEFAULT AS IDENTITY,
                     name varchar(100) NOT NULL,
                     author varchar(100) NOT NULL,
                     publicationYear int CHECK(publicationYear >= 1900),
                     personId int REFERENCES Person (id) ON DELETE SET NULL,
                     checkOutDate TIMESTAMP
);

truncate table Book;

insert into Book(name, author, publicationYear, personId, checkOutDate)
VALUES ('Java. Полное руководство', 'Герберт Шилдт', 2018, NULL, NULL),
       ('Java. Библиотека профессионала', 'Кей Хорстманн', 2020, NULL, NULL),
       ('Java. Эффективное программирование', 'Джошуа Блох', 2019, 1, '2023-01-22 11:23:56'),
       ('Spring в действии', 'Крейг Уоллс', 2022, 1, '2022-12-02 14:22:09');

select * from Book;